language: node_js
node_js:
    - "10.9.0"

branches:
  only:
    - master
    - develop

before_script:
  - yarn install --frozen-lockfile

script:
  - yarn buildlib
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: dist/angular6-json-schema-form-app
  